package eu.mcone.gameapi.api;

public enum Module {

    GAME_STATE_MANAGER,
    MAP_MANAGER,
    TEAM_MANAGER,
    REPLAY_MANAGER,
    REPLAY,
    BACKPACK_MANAGER,
    ACHIEVEMENT_MANAGER,
    PLAYER_MANAGER,
    KIT_MANAGER,
    ONE_PASS_MANAGER

}
