package eu.mcone.gameapi.api;

public enum Option {

    //BackpackManager
    BACKPACK_MANAGER_REGISTER_ALL_DEFAULT_CATEGORIES,
    BACKPACK_MANAGER_REGISTER_ANIMAL_CATEGORY,
    BACKPACK_MANAGER_REGISTER_GADGET_CATEGORY,
    BACKPACK_MANAGER_REGISTER_HAT_CATEGORY,
    BACKPACK_MANAGER_REGISTER_OUTFIT_CATEGORY,
    BACKPACK_MANAGER_REGISTER_TRAIL_CATEGORY,
    BACKPACK_MANAGER_REGISTER_EXCLUSIVE_CATEGORY,
    BACKPACK_MANAGER_USE_RANK_BOOTS,

    //AchievementManager
    ACHIEVEMENT_MANAGER_LOAD_ALL_ACHIEVEMENTS

}
