package eu.mcone.gameapi.api;

public enum Option {

    //BackpackManager
    BACKPACK_MANAGER_REGISTER_ALL_DEFAULT_CATEGORIES,
    BACKPACK_MANAGER_REGISTER_PET_CATEGORY,
    BACKPACK_MANAGER_REGISTER_GADGET_CATEGORY,
    BACKPACK_MANAGER_REGISTER_HAT_CATEGORY,
    BACKPACK_MANAGER_REGISTER_OUTFIT_CATEGORY,
    BACKPACK_MANAGER_REGISTER_TRAIL_CATEGORY,
    BACKPACK_MANAGER_REGISTER_EXCLUSIVE_CATEGORY,
    BACKPACK_MANAGER_USE_RANK_BOOTS,

    NORMAL_HOTBAR_WAITING_ITEMS,

    //KitManager
    KIT_MANAGER_CLEAR_INVENTORY_ON_KIT_SET,
    KIT_MANAGER_APPLY_KITS_ONCE,
    KIT_MANAGER_CHOOSE_KITS_FOR_SERVER_LIFETIME,

    //AchievementManager
    ACHIEVEMENT_MANAGER_LOAD_ALL_ACHIEVEMENTS,

    //ReplayManager
    DOWNLOAD_REPLAY_WORLDS,
    USE_REPLAY_VIEW_MANAGER,

    //TeamManager
    TEAM_MANAGER_DISABLE_RESPAWN,
    TEAM_MANAGER_DISABLE_WIN_METHOD,

    //GameHistory
    GAME_HISTORY_HISTORY_MODE

}
